### ISSUE TITLE
Fails to return highest priority cp if not in xml format 

### ISSUE THREAD

**Issue by NicoEsterhuyse** [dd4t/DD4T.Providers.SDLWeb8.5#2]
If no ct uri is specified `GetContent` returns an empty string result and not the highest priority component content as expected. It requires the content to be published as xml which is now discouraged in favor of json. This is the same issue as  dd4t/DD4T.Providers.SDLTridion2013sp1#8

**Comment by quirijnslings** [comment]
Release 2.5
